dist: bionic
language: python
install: pip install -U tox-travis coveralls
before_install: []

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=mypy
    - python: 3.7
      env: TOXENV=docs

    - python: 3.6
      env: TOXENV=py36
    - python: 3.8
      env: TOXENV=py38

script:
  - tox

after_success:
  - coveralls

