dist: xenial   # required for Python >= 3.7
language: python
python:
- "3.7"
- "3.6"
before_install:
  - wget http://ftp.it.debian.org/debian/pool/main/g/graphviz/graphviz_2.38.0-17_amd64.deb
  - sudo dpkg -i --force-all graphviz_2.38.0-17_amd64.deb
  - sudo apt-get install -f
  - sudo apt-get update
  - sudo apt-get install graphviz
install:
- pip install pipenv
- pipenv install --dev
script:
- tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: MarcoFavorito
  password:
    secure: jpoaAAhBmaPKND8O4ohVF0U+JqkbzDSRTxsS/rVzrUvjolCuEzzEN/1iusruuUXhZR1XxRONl1qc1Oh6T6TnNir0Vi1o9vPgX2BcsHgFqxV0O7MeljOK8yryfcff1qnSCzOI/4zz5pudNIJM/CI8ymHhA+CQPHmmMy6a0k1r9uJvjqtuLsoSPpFSzaoCxLnJ4AJ7huKDJWm+nW2Q6M0+ZWWHy8AbQayzw9F+McCLV+2fRZoJrubQkRjoXQXJH9s0NwzHvuZMi3VjjPdrZvhvw/SNxSrqX82TCRHMgCXFj8nbDTHfkcBQ3VkB9AjoLpdgsvz/LF8TtM93PFKQmH6lyHZku5LFNVxeHhU7+Bme/8M285aL8EDkSY5+hyg9dGaQZdIDViUaqaUtzq+cfp0sL6mEBjrkNsShl1WTC0UNrzy/wAjHWIk5IvsAocDckg6LQuYLONcWq+wW05oH5MZhVm9Vq/zbBPyLPZvGIATtatugJtekIWojWH7PRUNjBFL+OIfGQZBSSTKbVatA3RCxFL1ilAo+mQKblL4daROSEu8aGPpR2qpDa7QYDYq4Cgb84h0fbAhhTIt81kf8Vh5xCGlika4kUKPDNGyKuoITjh3jOOxwo5T5v5d9qhY+6jNOsUQcuGTnrFSq7JdfRN6412lUvVqPTZY8dpPNuzL229Q=
  on:
    tags: true
    repo: marcofavorito/pythomata
    python: 3.7
after_success:
  - codecov
